// ACTION TYPES

export const ADD_EXPENSES = 'ADD_EXPENSES';
export const ADD_PURCHASE = 'ADD_PURCHASE';
export const ADD_INITIAL_VALUES = 'ADD_INITIAL_VALUES';
export const DECREMENT_AMOUNT_OF_DAYS = 'DECREMENT_AMOUNT_OF_DAYS';
